### Test Auth Routes

### Test /register route
POST http://localhost:3000/api/v1/auth/register
Content-Type: application/json

{
    "email": "jonarobledo@gmail.com",
    "password": "asdqwe123"
}

### Test /login route with User validated
POST http://localhost:3000/api/v1/auth/login
Content-Type: application/json

{
    "email": "jonarobledo@gmail.com",
    "password": "asdqwe123"
}

### Test /getUser with Cookies
GET http://localhost:3000/api/v1/auth/getUser

### Test /login route with User email invalidated
POST http://localhost:3000/api/v1/auth/login
Content-Type: application/json

{
    "email": "jonarobledo_1@gmail.com",
    "password": "asdqwe123"
}

### Test /login route with User password invalidate
POST http://localhost:3000/api/v1/auth/login
Content-Type: application/json

{
    "email": "jonarobledo@gmail.com",
    "password": "asdqwe123456"
}

### Test /getUser route to Token validate with Bad Token (Bearer Token)
GET http://localhost:3000/api/v1/auth/getUser
Authorization: Bearer asdqwe123

### Test /getUser route without Token
GET http://localhost:3000/api/v1/auth/getUser

### Test /getUser route to Token validate (Bearer Token)
GET http://localhost:3000/api/v1/auth/getUser
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1aWQiOiI2Nzg0MmMyYmJlODRlZTM0NzdkZTI2Y2YiLCJpYXQiOjE3NTIyOTc5ODMsImV4cCI6MTc1MjMwNTE4M30._I_5EdKQX2M1WkPCztRpoXW2D8sHGbXyLgbYih0t2jk